### ISSUE TITLE
Problems using with VS Code

### ISSUE THREAD

**Issue by vknabel** [TobiasYin/go-lsp#2]
Hi @TobiasYin,

First of all, thanks for the great project!

Weirdly enough, I can't get the example working. No errors will be logged, but no feature is working. Even replacing go-lsp handlers with `panic` does not work. I tried with VS Code and a self-written extension (see details spoiler below).

Do you have some working example code for client and server? No matter for which client editor.
Or do you have an idea of what's missing?

<details>
Below some code I've used for my vscode extension, if it helps you.

I started with a blank VS Code extension and followed [language-server-extension-guide](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide).
Additionally I set the `TransportKind.stdio` to match go-lsp's defaults.

```
const serverOptions: ServerOptions = {
    command: "/path/to/compiled/go-lsp-master/example/main",
    args: [],
    transport: TransportKind.stdio, // also tried every other option
};
const clientOptions: LanguageClientOptions = {
    documentSelector: [
      { scheme: "file", language: "example" },
      { scheme: "file", pattern: "*.example" },
      { scheme: "file", language: "go" }, // to ensure there is no bug in the contributed language definition
      { scheme: "file", pattern: "*.go" },
    ]
   // also tried outputChannel and traceOutputChannel
}
client = new LanguageClient(
    "example",
    "Example Language Server",
    serverOptions,
    clientOptions
  );

client.onReady().then(() => {
    console.log("Example client ready"); // will NOT be logged
});

client.start();
```

</details>

**Comment by vknabel** [comment]
Later I tried the same with Atom, because it seems to have better debugging support for custom a lsp.
After I commented out all `fmt.Println` from go-lsp, the communication between client and server worked.
Probably for `stdio` we need to pick a different logging destination than stdout. E.g. writing to the system logs.

**Comment by TobiasYin** [comment]
I'm sorry to reply the issue so late. I debug the example, and find that's a bug. The Program output log and response to stdout, and It will make vscode confuse. I was already fixed the bug. BTW, I set the MIT license to project, feel free to use. 

You can try again with the newest code.

**Comment by vknabel** [comment]
Thanks for the fix! Though I have to admit, I switched to [github.com/tliron/glsp](https://github.com/tliron/glsp) as it has support for `textDocument/semanticTokens/full`, which has been essential for my project.

I haven't tried your fix, but from reading the diff, I'd agree that this issue can be closed. 
Thanks a lot anyways!
